/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Editor Animations",
  "description": "Adds smooth animations to various aspects of the editor!",
  "credits": [
    {
      "name": "reflow",
      "link": " https://github.com/mmmmaaaaarrrrrrkkkkkkkk"
    },
    {
      "name": "SharkPool"
    }
  ],
  "info": [
    {
      "type": "notice",
      "text": "Animations will not play if you have 'reduce motion' enabled on your device/browser.",
      "id": "reduced-motion-notice"
    }
  ],
  "settings": [
    {
      "id": "animateButtons",
      "name": "Animate Buttons",
      "default": true,
      "type": "boolean"
    },
    {
      "id": "animateLibraries",
      "name": "Animate Libraries (costumes, sprites, sounds, etc)",
      "default": true,
      "type": "boolean"
    },
    {
      "id": "animateModals",
      "name": "Animate Modals (create variable/list, custom block, etc)",
      "default": true,
      "type": "boolean"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "new", "theme"
  ],
  "enabledByDefault": true
};
export default manifest;
